version: '3'
services:
  react-native:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../:/project 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm 
      - /etc/machine-id:/etc/machine-id
      - /run/user/$UID/pulse:/run/user/"$DOCKER_UID"/pulse
      - /var/lib/dbus:/var/lib/dbus
    command: "/opt/android-sdk-linux/tools/emulator -use-system-libs -avd nameOfAvd"  
    container_name: "test"
    privileged: true