version: '3'
services:
  dev-environment:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../:/project 
    command: "react-native run-android"  
    container_name: react-native